import { NgModule, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Routes } from '@angular/router';
import { LoginComponent } from './login/login.component';
import { UserRegisterComponent } from './user-register/user-register.component';
import { RequirementsComponent } from './requirements/requirements.component';
import { SubmissionsComponent } from './submissions/submissions.component';
import { AddNewRequirementComponent } from './add-new-requirement/add-new-requirement.component';
import { EditRequirementComponent } from './edit-requirement/edit-requirement.component';
import { AddNewSubmissionsComponent } from './add-new-submissions/add-new-submissions.component';
import { ManageUsersComponent } from './manage-users/manage-users.component';
import { AddUserComponent } from './add-user/add-user.component';
import { SubmissionByRequirementComponent } from './submission-by-requirement/submission-by-requirement.component';
import { ManageClientComponent } from './manage-client/manage-client.component';
import { AddClientComponent } from './add-client/add-client.component';
import { RecruiterEditSubmissionsComponent } from './recruiter-edit-submissions/recruiter-edit-submissions.component';
import { ManageCandidateComponent } from './manage-candidate/manage-candidate.component';
import { AddCandidateComponent } from './add-candidate/add-candidate.component';
import { GenerateReportComponent } from './generate-report/generate-report.component';
import { RequirementDetailComponent } from './requirement-detail/requirement-detail.component';
import { EditUserComponent } from './edit-user/edit-user.component';
import { EditCandidateComponent } from './edit-candidate/edit-candidate.component';
import { EditClientComponent } from './edit-client/edit-client.component';
import { AddTeamComponent } from './add-team/add-team.component';
import { ManageTeamComponent } from './manage-team/manage-team.component';
import { EditTeamComponent } from './edit-team/edit-team.component';
import { EditSubmissonComponent } from './edit-submisson/edit-submisson.component';
import { AdminDashboardComponent } from './dashboard/admin-dashboard/admin-dashboard.component';
import { UserSubmissionsComponent } from './user-submissions/user-submissions.component';
import { TeamSubmissionsComponent } from './team-submissions/team-submissions.component';
import { ClientRequirementsComponent } from './client-requirements/client-requirements.component';
import { DeleteTeamComponent } from './delete-team/delete-team.component';
import { TeamSubmissionStatusComponent } from './team-submission-status/team-submission-status.component';
import { ClientSubmissionStatusComponent } from './client-submission-status/client-submission-status.component';
import { RecruiterComparisonComponent } from './recruiter-comparison/recruiter-comparison.component';
import { TeamComparisonComponent } from './team-comparison/team-comparison.component';
import { AccMgrDashboardComponent } from './dashboard/acc-mgr-dashboard/acc-mgr-dashboard.component';
import { RecruiterDashboardComponent } from './dashboard/recruiter-dashboard/recruiter-dashboard.component';
import { ForgotPasswordComponent } from './forgot-password/forgot-password.component';
import { RecruiterSubmissionsStatusComponent } from './recruiter-submissions-status/recruiter-submissions-status.component';
import { GraphExpansationComponent } from './graph-expansation/graph-expansation.component';
import { InterviewHistoryComponent } from './interview-history/interview-history.component';
import { DeleteUserComponent } from './delete-user/delete-user.component';
import { CandidateReportComponent } from './candidate-report/candidate-report.component';
import { InProgressInterviewsComponent } from './in-progress-interviews/in-progress-interviews.component';
import { JoiningDateComponent } from './joining-date/joining-date.component';
import { SelectedSubmissionComponent } from './selected-submission/selected-submission.component';
import { SearchCandidatesComponent } from './search-candidates/search-candidates.component';
import { SendMailComponent } from './send-mail/send-mail.component';
import { DeleteRequirementComponent } from './delete-requirement/delete-requirement.component';
import { DeleteSubmissionComponent } from './delete-submission/delete-submission.component';
import { SearchCandidateEmailComponent } from './search-candidate-email/search-candidate-email.component';
import { VendorMailComponent } from './vendor-mail/vendor-mail.component';
import { TimeSheetComponent } from './time-sheet/time-sheet.component';
import { TimeSheetDetailsComponent } from './time-sheet-details/time-sheet-details.component';
import { TimesheetReportComponent } from './timesheet-report/timesheet-report.component';
import { LeaveRequestComponent } from './leave-request/leave-request.component';
import { CreateHolidayComponent } from './create-holiday/create-holiday.component';
import { HolidayListComponent } from './holiday-list/holiday-list.component';
import { CancelLeaveRequestComponent } from './cancel-leave-request/cancel-leave-request.component';
import { LeaveManageComponent } from './leave-manage/leave-manage.component';
import { DiceIntergrationComponent } from './dice-intergration/dice-intergration.component';
import { AddDiceComponent } from './add-dice/add-dice.component';
import { DiceLoginComponent } from './dice-login/dice-login.component';
import { DiceDetailViewComponent } from './dice-detail-view/dice-detail-view.component';
import { EditDiceComponent } from './edit-dice/edit-dice.component';



export const appRoutes: Routes = [
  { path: '', redirectTo: '/login', pathMatch: 'full' },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: UserRegisterComponent },
  { path: 'admin-dashboard', component: AdminDashboardComponent },
  { path: 'requirements', component: RequirementsComponent },
  { path: 'submissions', component: SubmissionsComponent },
  { path: 'add-new-requirement', component: AddNewRequirementComponent },
  { path: 'edit-requirement/:id', component: EditRequirementComponent },
  { path: 'add-new-submission', component: AddNewSubmissionsComponent },
  { path: 'add-new-submission/:id', component: AddNewSubmissionsComponent },
  { path: 'manage-users', component: ManageUsersComponent },
  { path: 'add-user', component: AddUserComponent },
  { path: 'submission-by-requirement/:id', component: SubmissionByRequirementComponent },
  { path: 'manage-client', component: ManageClientComponent },
  { path: 'add-client', component: AddClientComponent },
  { path: 'recruiter-edit-submissions/:id', component: RecruiterEditSubmissionsComponent },
  { path: 'manage-candidate', component: ManageCandidateComponent },
  { path: 'add-candidate', component: AddCandidateComponent },
  { path: 'generate-report', component: GenerateReportComponent },
  { path: 'requirement-detail/:id', component: RequirementDetailComponent },
  { path: 'edit-user/:id', component: EditUserComponent },
  { path: 'edit-client/:id', component: EditClientComponent },
  { path: 'edit-candidate/:id', component: EditCandidateComponent },
  { path: 'manage-team', component: ManageTeamComponent },
  { path: 'add-team', component: AddTeamComponent },
  { path: 'edit-team/:id', component: EditTeamComponent },
  { path: 'edit-submission/:id', component: EditSubmissonComponent },
  { path: 'user-submisson/:id/:fromDate/:toDate', component: UserSubmissionsComponent },
  { path: 'team-submisson/:id/:fromDate/:toDate', component: TeamSubmissionsComponent },
  { path: 'client-requirements/:id/:fromDate/:toDate', component: ClientRequirementsComponent },
  { path: 'team-submissions-status/:id/:status/:fromDate/:toDate', component: TeamSubmissionStatusComponent },
  { path: 'client-submissions-status/:id/:status/:fromDate/:toDate', component: ClientSubmissionStatusComponent },
  { path: 'recruiter-comparison/:id/:status/:fromDate/:toDate', component: RecruiterComparisonComponent },
  { path: 'team-comparison/:id/:status/:fromDate/:toDate', component: TeamComparisonComponent },
  { path: 'recruiter-submissions-status/:id/:status/:fromDate/:toDate', component: RecruiterSubmissionsStatusComponent },
  { path: 'delete-team/:id', component: DeleteTeamComponent },
  { path: 'delete-user/:id', component: DeleteUserComponent },
  { path: 'mgr-dashboard', component: AccMgrDashboardComponent },
  { path: 'tl-dashboard', component: AccMgrDashboardComponent },
  { path: 'recruiter-dashboard', component: RecruiterDashboardComponent },
  { path: 'forgot-password', component: ForgotPasswordComponent },
  { path: 'graph-expand', component: GraphExpansationComponent },
  { path: 'interview-history', component: InterviewHistoryComponent },
  { path: 'candidate-report', component: CandidateReportComponent },
  { path: 'in-progress-interviews', component: InProgressInterviewsComponent },
  { path: 'joining-date', component: JoiningDateComponent },
  { path: 'selected-submissions', component: SelectedSubmissionComponent },
  { path: 'search-candidates', component: SearchCandidatesComponent },
  { path: 'search-candidates-email', component: SearchCandidateEmailComponent },
  { path: 'send-mail', component: SendMailComponent },
  { path: 'delete-requirement', component: DeleteRequirementComponent },
  { path: 'delete-submission', component: DeleteSubmissionComponent },
  { path: 'search-vendors', component: VendorMailComponent },
  { path: 'time-sheet', component: TimeSheetComponent },
  { path: 'time-sheet-expand', component: TimeSheetDetailsComponent },
  { path: 'time-sheet-report', component: TimesheetReportComponent },
  { path: 'leave-request', component: LeaveRequestComponent },
  { path: 'create-holiday', component: CreateHolidayComponent },
  { path: 'holiday-list', component: HolidayListComponent },
  { path: 'cancel-leave-request', component: CancelLeaveRequestComponent },
  { path: 'cancel-leave-request/:id', component: CancelLeaveRequestComponent },
  { path: 'leave-manage', component: LeaveManageComponent },
  { path: 'dice-login', component: DiceLoginComponent },
  { path: 'dice-view', component: DiceIntergrationComponent },
  { path: 'add-dice', component: AddDiceComponent }, 
  { path: 'edit-dice', component: EditDiceComponent }, 
  { path: 'dice-detail-view/:id', component: DiceDetailViewComponent }, 
];


// @NgModule({
//   imports: [RouterModule.forRoot(appRoutes, { useHash: true })],
//   exports: [RouterModule]
// })
// export class AppRoutingModule { }
